<?php
// module/Album/view/album/album/add.phtml:

$title = 'Agregar Nuevo Cargo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cargo', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idcargo'));
echo $this->formRow($form->get('descripcion'));
echo $this->formRow($form->get('activo'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();