<?php
// module/Album/view/album/album/index.phtml:

$title = 'Cargos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cargo', array('action'=>'add'));?>">Agregar Nuevo Cargo</a>
</p>

<table class="table">
<tr>
    <th>Nro. Cargo</th>
    <th>Descripcion</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($cargos as $cargo) : ?>
<tr>
    <td><?php echo $this->escapeHtml($cargo->idcargo);?></td>
    <td><?php echo $this->escapeHtml($cargo->descripcion);?></td>
    <td>
        <a href="<?php echo $this->url('cargo',
            array('action'=>'edit', 'id' => $cargo->id));?>">Editar</a>
        <a href="<?php echo $this->url('cargo',
            array('action'=>'delete', 'id' => $cargo->id));?>">Eliminar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>